# Generated by Django 5.1.2 on 2025-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('drive_link', models.URLField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Live', 'Live'), ('Dihentikan', 'Dihentikan')], max_length=50)),
            ],
        ),
    ]
